name: daltonic
description: A very lite and minimal subsonic server
version: 0.0.1
repository: https://github.com/julywitch/daltonic

environment:
  sdk: ^3.6.0

dependencies:
  audio_metadata_reader: ^1.1.0
  convert: ^3.1.2
  crypto: ^3.0.6
  path: ^1.9.1
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  sqflite_common_ffi: ^2.3.4+4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
